### ISSUE TITLE
Examples for backup to Azure Blob storage?

### ISSUE THREAD

**Issue by nimaaj93** [arangodb/kube-arangodb#1073]
I have been trying to use the backup feature of the operator on Azure Blob Storage. Following the rclone docs for azureblob, I was able to connect and sync files using the command line but when I add the same credentials on json token and create the backup resource base on it, I see no actions happening and when I describe the backup resource, I see no events there.

My backup yaml:

```
apiVersion: "backup.arangodb.com/v1alpha"
kind: "ArangoBackup"
metadata:
  name: "testbackup"
  namespace: "arango"
spec:
  upload:
    repositoryURL: "azure://mystorageaccount"
    credentialsSecretName: "backupsecret"
  deployment:
    name: "my-deployment"
```

And my json token:

```
{"azure":{"account": "mystorageaccount","key": "mykey"}}
```

I also tried using `azureblob` instead of `azure` for provider as well as other authentication methods described on rclone page.

it would be really nice to have an example of the backup similar to S3 mentioned in the documentation.
