### ISSUE TITLE
Not able to set the persistent volumes to SSD even after setting the storageClassName as "premium-rwo"

### ISSUE THREAD

**Issue by Surezt22** [arangodb/kube-arangodb#1187]
Hello, 

I have been trying to set the cluster arango in GKE using the below YAML after installing the required **kube-arangodb** operators.
```
apiVersion: "database.arangodb.com/v1alpha"
kind: "ArangoDeployment"
metadata:
  name: "distributed-arango"
  namespace: dev
spec:
  mode: Cluster
  metrics:
    mode: sidecar
    enabled: true
    image: 'arangodb/arangodb-exporter:0.1.7'
    tls: false
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9101'
    prometheus.io/scrape_interval: '5s'
  image: "arangodb/arangodb:3.7.10"
  environment: Production
  imagePullPolicy: Always
  tls:
    caSecretName: None
  agents:
    count: 3
    args:
      - --log.level=debug
    nodeSelector:
      cloud.google.com/gke-nodepool: development-node-pool
  dbservers:
    count: 2
    args:
      - --log.level=debug
      - --log.performance=true
      - --log.prefix="ARANGO_LOGS"
      - --query.slow-threshold=40
      - --server.statistics=false
    resources:
      limits:
            cpu: 6000m
            memory: 32Gi
      requests:
        cpu: 6000m
        memory: 32Gi
    volumeClaimTemplate:
     spec:
       accessModes:
       - ReadWriteOnce
       resources:
         requests:
           storage: 80Gi
       volumeMode: Filesystem
    storageClassName: premium-rwo
    nodeSelector:
      cloud.google.com/gke-nodepool: development-node-pool
  coordinators:
    count: 3
    args:
      - --log.level=debug
      - --log.role=true
      - --log.performance=true
      - --log.prefix=ARANGO_LOGS
      - --query.cache-mode="on"
      - --query.slow-threshold=60
      - --cluster.default-replication-factor=2
    resources:
        limits:   
            cpu: 6000m
            memory: 32Gi
        requests:
          cpu: 6000m
          memory: 32Gi
    nodeSelector:
      cloud.google.com/gke-nodepool: development-node-pool
```

Even though I set the storageClassName for the **dbservers** component under volumeClaimTemplate to be  **premium-rwo**, the PVC is getting created with the standard class and not SSD.   What should I do to ensure to make the PV as type **pd-ssd**.
