### ISSUE TITLE
Change toleration and nodeselector

### ISSUE THREAD

**Issue by heroic** [arangodb/kube-arangodb#1220]
We have a deployment in our production cluster, but due to some changes in our setup, we now need to change the tolerations for the cluster. Editing the deployment yaml does not seem to be working, as it resets to original version after saving and exiting. How can we make the changes without losing any data?

**Comment by ajanikow** [comment]
Hello!

Can you share your YAML? We have tests for tolerations, and together with 1.2.23, we will allow changing tolerations in runtime (so without restarts).

Usually, it works as expected (unless there is a typo or tolerations are placed in the wrong section).

Best Regards,
Adam.

**Comment by sajangupta74** [comment]
Hello @ajanikow, appologies for late reply, here is the yaml
````
# Source: arango/templates/arango-deployment.yaml
apiVersion: "database.arangodb.com/v1"
kind: "ArangoDeployment"
metadata:
  name: arangodb
  annotations:
    meta.helm.sh/release-name: 'arangodb'
  namespace: jx-production
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  image: arangodb:3.9.2
  mode: Cluster
  metrics:
    mode: sidecar
    enabled: true
    image: 'arangodb/arangodb-exporter:0.1.8'
    tls: false
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9101'
    prometheus.io/scrape_interval: '5s'
  monitoring:
    enabled: false
  tls:
    caSecretName: None
  environment: Production
  coordinators:
  #     nodeSelector:
  #       cloud.google.com/gke-spot: "true"
  #     tolerations:
  #     - key: pool
  #       operator: Equal
  #       value: spot
  #       effect: NoSchedule
  agents:
  #     nodeSelector:
  #       cloud.google.com/gke-spot: "true"
  #     tolerations:
  #     - key: pool
  #       operator: Equal
  #       value: spot
  #       effect: NoSchedule
  dbservers:
    #     nodeSelector:
    #       cloud.google.com/gke-spot: "true"
    #     tolerations:
    #     - key: pool
    #       operator: Equal
    #       value: spot
    #       effect: NoSchedule
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 32Gi
        volumeMode: Filesystem

````

[arangodb-deployment.txt](https://github.com/arangodb/kube-arangodb/files/10335142/arangodb-deployment.txt)
