### ISSUE TITLE
Operator on mode single spinning up LoadBalancer

### ISSUE THREAD

**Issue by DarkNeedle** [arangodb/kube-arangodb#1226]
All

Below is a simple deployment for the mode single. As Vultr requires a minimum storage size of 40G this has been added. However, is there a reason why singe mode would try to spin up a LoadBalancer?

kind: "ArangoDeployment"
metadata:
  name: "arangodb-dev-single"
spec:
  mode: Single
  image: 'arangodb/arangodb:3.10.2'
  single:
    storageClassName: vultr-block-storage-hdd
    resources:
      requests:
        storage: 40Gi

Thanks

**Comment by jwierzbo** [comment]
LoadBalancer is default service type in kube-arangodb for external access.
You can change it e.g. to the NodePort:

```yaml
apiVersion: database.arangodb.com/v1
kind: ArangoDeployment
metadata:
  name: cluster
spec:
  image: arangodb/arangodb:3.10.2
  mode: Single
  externalAccess:
    type: NodePort
```
