### ISSUE TITLE
How can I define ARANGODB_OVERRIDE_DETECTED_TOTAL_MEMORY in arangodb cluster

### ISSUE THREAD

**Issue by Aaron-Ritter** [arangodb/kube-arangodb#1253]
I tried to define ARANGODB_OVERRIDE_DETECTED_TOTAL_MEMORY : 
https://www.arangodb.com/docs/stable/programs-starter-options.html#passing-environment-variables

In the args definition:
https://www.arangodb.com/docs/stable/deployment-kubernetes-deployment-resource.html#specgroupargs-string

This did not work and then I tried addition overrideDetectedTotalMemory
https://www.arangodb.com/docs/stable/deployment-kubernetes-deployment-resource.html#specgroupoverridedetectedtotalmemory-bool

in both cases the initialization fails

e.g.
```
apiVersion: "database.arangodb.com/v1alpha"
kind: "ArangoDeployment"
metadata:
  name: "arango-cluster"
  namespace: arangodb
spec:
  mode: Cluster
  environment: Production
  tls:
    caSecretName: None
  agents:
    count: 3
    resources:
      requests:
        storage: 8Gi
    storageClassName: nfs-client-fast
  dbservers:
    count: 3
    overrideDetectedTotalMemory: true
    args:
     - --envs.dbservers.ARANGODB_OVERRIDE_DETECTED_TOTAL_MEMORY=1G
    resources:
      requests:
        storage: 8Gi
    storageClassName: nfs-client-fast
  coordinators:
    count: 3
    overrideDetectedTotalMemory: true
    args:
     - --envs.coordinators.ARANGODB_OVERRIDE_DETECTED_TOTAL_MEMORY=1G
  image: "arangodb/arangodb:3.10.3"
```

**Comment by jwierzbo** [comment]
@Aaron-Ritter you shouldn't define `ARANGODB_OVERRIDE_DETECTED_TOTAL_MEMORY` manually. The link which you refer is for **ArangoDB-starter** case

In your code you made mistake: instead of `requests.storage` you should set `limits.memory`

I've prepared proper documentation for that feature here: https://github.com/arangodb/kube-arangodb/pull/1258/files

**Comment by Aaron-Ritter** [comment]
the request storage is related to NFS, so unrelated to memory :).

but i will try your suggestion :)

**Comment by Aaron-Ritter** [comment]
Thanks @jwierzbo this did the trick! I was aware about the k8s resource definitions but thought I have to define it on the arangodb level.

```
apiVersion: "database.arangodb.com/v1alpha"
kind: "ArangoDeployment"
metadata:
  name: "arango-cluster"
  namespace: arangodb
spec:
  mode: Cluster
  environment: Production
  tls:
    caSecretName: None
  agents:
    count: 3
    overrideDetectedTotalMemory: true
    resources:
      limits:
        memory: 1Gi
      requests:
        storage: 8Gi
    storageClassName: nfs-client-fast
  dbservers:
    count: 3
    overrideDetectedTotalMemory: true
    resources:
      limits:
        memory: 1Gi
      requests:
        storage: 8Gi
    storageClassName: nfs-client-fast
  coordinators:
    count: 3
    overrideDetectedTotalMemory: true
    resources:
      limits:
        memory: 1Gi
  image: "arangodb/arangodb:3.10.3"
```
