### ISSUE TITLE
Backups created by policy can be deleted by ArgoCD

### ISSUE THREAD

**Issue by wyattwalter** [arangodb/kube-arangodb#1260]
We are using ArgoCD to manage both the kube-arangodb operator install as well as a number of ArangoDB deployment objects. I noticed today that some backups that are being scheduled by our BackupPolicy are simply missing. Looking through the event logs, it looks like those backups were indeed created, and then subsequently deleted by ArgoCD.

I believe that what has been happening is that the backup is created on the schedule without an ownerReference object by the policy handler without an ownerReference but it does do a copy of the annotations from the deployment such as `argocd.argoproj.io/instance`. Then some job is coming along and adding that ownerReference to the backup object. However, if ArgoCD tries to sync with `prune` set to `true` on the application in the meantime, it deletes the backup object. This happens because at that moment the object says it's managed by an ArgoCD project (`argocd.argoproj.io/instance` is set), but the application doesn't have that resource and there's no ownerReference to follow so ArgoCD can know that it's owned by the cluster.

I think that ArgoCD is behaving correctly in this case, and that the ownerReference should be added to the object by the policy handler at creation time.

**Comment by jwierzbo** [comment]
We have `ownerReference` set in place in every Backup object

```
➜ kubectl get arangobackup backup-1 -o yaml
apiVersion: backup.arangodb.com/v1
kind: ArangoBackup
metadata:
  annotations:
  finalizers:
  - arangobackups.backup.arangodb.com/cleanup
  generation: 2
  name: backup-1
  namespace: test
  ownerReferences:
  - apiVersion: database.arangodb.com/v1
    controller: true
    kind: ArangoDeployment
    name: single
    uid: d264d3a9-afb3-4acf-96e7-e177570b3f10
```
