### ISSUE TITLE
Issue deploying arangodb on EKS, can't add tolerations to 'Image ID' pod

### ISSUE THREAD

**Issue by mfractal** [arangodb/kube-arangodb#1280]
Hi, we have karpenter provisioners setup on our EKS cluster such that each pod has to have a certain toleration in order to be able to get scheduled on a node.

I've successfully deployed the arango operators via helm chart 
like so

```
operator:
  image: arangodb/kube-arangodb:1.2.24
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []

  scope: legacy
  
  architectures:
  - arm64

  debug: false

  args: []

  service:
    type: ClusterIP

  annotations: {}

  resources:
    limits:
      cpu: 1
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 256Mi

  securityContext:
    runAsUser: 1000

  replicaCount: 2

  updateStrategy:
    type: Recreate

  allowChaos: false

  nodeSelector:
        kubernetes.io/arch: arm64


  enableCRDManagement: true

  features:
    deployment: true
    deploymentReplications: false
    storage: true
    backup: true
    apps: false
    k8sToK8sClusterSync: false

  images:
    base: alpine:3.11
    metricsExporter: arangodb/arangodb-exporter:0.1.7
    arango: arangodb/arangodb:latest

  tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: app

rbac:
  enabled: true
  extensions:
    monitoring: true
    acs: true
    at: true
    debug: false
```

they show as running no problem.

Now i am trying to create ArangoDeployment with the following declaration :

```
apiVersion: "database.arangodb.com/v1"
kind: "ArangoDeployment"
metadata:
  name: "arangodb-stg"
spec:
  mode: Cluster
  environment: Production
  architecture:
    - arm64
  metrics:
    enabled: true
  agents:
    nodeSelector:
      kubernetes.io/arch: arm64
    tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: app
    count: 3
    resources:
      requests:
        storage: 8Gi
    storageClassName: gp2
  dbservers:
    nodeSelector:
      kubernetes.io/arch: arm64
    tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: app
    count: 3
    resources:
      requests:
        storage: 100Gi
    storageClassName: gp2
  coordinators:
    tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: app
    nodeSelector:
      kubernetes.io/arch: arm64
    count: 3
```

But i am running into an issue. The first pod that the operator schedules is the Image ID pod and it doesn't get the needed tolerations in order to get scheduled where i want it.
There isn't a group in ArangoDeployment for the Image ID pod tolerations / node selector. How can i overcome this limitation ?

```
Name:             arangodb-stg-id-818a6f
Namespace:        arangodb
Priority:         0
Service Account:  default
Node:             <none>
Labels:           app=arangodb
                  arango_deployment=arangodb-stg
                  deployment.arangodb.com/member=818a6f
                  role=id
Annotations:      kubernetes.io/psp: eks.privileged
Status:           Pending
IP:
IPs:              <none>
Controlled By:    ArangoDeployment/arangodb-stg
Containers:
  server:
    Image:      arangodb/arangodb:3.9.3
    Port:       8529/TCP
    Host Port:  0/TCP
    Command:
      /usr/sbin/arangod
      --database.directory=/data
      --log.output=+
      --server.authentication=false
      --server.endpoint=tcp://[::]:8529
    Environment:  <none>
    Mounts:
      /data from arangod-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-m7wqc (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  arangod-data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  kube-api-access-m7wqc:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.alpha.kubernetes.io/unreachable:NoExecute op=Exists for 5s
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 5s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 5s
Events:
  Type     Reason              Age                   From               Message
  ----     ------              ----                  ----               -------
  Warning  FailedProvisioning  5m23s (x11 over 25m)  karpenter          Failed to provision new node, incompatible with provisioner "app", incompatible requirements, key kubernetes.io/arch, kubernetes.io/arch In [arm64] not in kubernetes.io/arch In [amd64]; incompatible with provisioner "app-arm", did not tolerate dedicated=app:NoSchedule; incompatible with provisioner "delivery", did not tolerate dedicated=delivery:NoSchedule
  Warning  FailedProvisioning  3m59s (x10 over 24m)  karpenter          Failed to provision new node, incompatible with provisioner "app-arm", did not tolerate dedicated=app:NoSchedule; incompatible with provisioner "delivery", did not tolerate dedicated=delivery:NoSchedule; incompatible with provisioner "app", incompatible requirements, key kubernetes.io/arch, kubernetes.io/arch In [arm64] not in kubernetes.io/arch In [amd64]
  Warning  FailedScheduling    37s (x6 over 26m)     default-scheduler  0/11 nodes are available: 1 node(s) had untolerated taint {dedicated: delivery}, 4 node(s) had untolerated taint {dedicated: app}, 6 node(s) didn't match Pod's node affinity/selector. preemption: 0/11 nodes are available: 11 Preemption is not helpful for scheduling.
  Warning  FailedProvisioning  34s (x10 over 26m)    karpenter          Failed to provision new node, incompatible with provisioner "delivery", did not tolerate dedicated=delivery:NoSchedule; incompatible with provisioner "app", incompatible requirements, key kubernetes.io/arch, kubernetes.io/arch In [arm64] not in kubernetes.io/arch In [amd64]; incompatible with provisioner "app-arm", did not tolerate dedicated=app:NoSchedule
```

**Comment by jwierzbo** [comment]
If you just need to add a toleration for `ID` pod then:
```
apiVersion: "database.arangodb.com/v1"
kind: "ArangoDeployment"
metadata:
  name: "arangodb-stg"
spec:
  mode: Cluster
  environment: Production
  architecture:
    - arm64
  metrics:
    enabled: true
  id:
    nodeSelector:
      kubernetes.io/arch: arm64
    tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: app
```

**Comment by mfractal** [comment]
hmm ok did that but now it seems it's pulling the wrong image architecture, it's scheduled on arm node but trying to execute amd64 image ? 

```
exec /usr/sbin/arangod: exec format error                                                                                                      ││ 
Stream closed EOF for arangodb/arangodb-stg-id-818a6f (server)
```

Here's the yaml used :
```
apiVersion: "database.arangodb.com/v1"
kind: "ArangoDeployment"
metadata:
  name: "arangodb-stg"
spec:
  mode: Cluster
  id:
    nodeSelector:
      kubernetes.io/arch: arm64
    tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: app
  environment: Production
  architecture:
    - arm64
  metrics:
    enabled: true
  agents:
    nodeSelector:
      kubernetes.io/arch: arm64
    tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: app
    count: 3
    resources:
      requests:
        storage: 8Gi
    storageClassName: gp2
  dbservers:
    nodeSelector:
      kubernetes.io/arch: arm64
    tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: app
    count: 3
    resources:
      requests:
        storage: 100Gi
    storageClassName: gp2
  coordinators:
    tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: app
    nodeSelector:
      kubernetes.io/arch: arm64
    count: 3
  image: "arangodb/arangodb:3.9.3"
```
