### ISSUE TITLE
Docker entrypoint not running in ArangoDeployment

### ISSUE THREAD

**Issue by ricsi046** [arangodb/kube-arangodb#1396]
The official arangodb docker image (https://hub.docker.com/_/arangodb) has an entrypoint script that can be used to import user defined functions from the `docker-entrypoint-initdb.d` folder. It works fine when I run my docker image, UDFs get imported. If I use the image in an `ArangoDeployment`, the entrypoint script is skipped. I verified it by adding a line in the dockerfile that deletes the `entrypoint.sh` file, there was no error, the database was still accessible, so I assume ArangoDeployment has its own entrypoint and ignores docker entrypoint. Is that correct? If so, how can I get the UDFs imported?

Sample helm chart:

[arango_helm.zip](https://github.com/arangodb/kube-arangodb/files/12499163/arango_helm.zip)

**Comment by ajanikow** [comment]
Hello!

We override default entrypoint in the pods (configurable via https://github.com/arangodb/kube-arangodb/blob/master/docs/api/ArangoDeployment.V1.md#specagentsentrypoint-string - for all groups) - please, be aware we are working on the generator, so not all fielda are represented correctly.

It would be best if you can specify job (k8s job) in your chart (with init container which waits for deployment to be up - wait for UpToDate condition in the ArangoDeployment .status.conditions[]).

Otherwise, you can use ArangoJob which are designed for this use case (if you are interested, we can provide doc for your use-case).

We are are planning to provide post-bootstrap jobs, which allow users to do all of the imports (of the users, functions and databases) before bootstrap is marked as completed.

Best Regards,
Adam.

**Comment by ricsi046** [comment]
Thanks for your answer. I will give the init container solution a try and update this issue with the result.

**Comment by ricsi046** [comment]
I couldn't get it to work. I'm a beginner in this area, but I think init containers can't be used with a CRD like ArangoDeployment, they get ignored, for example I can't specify init container here:

```
apiVersion: database.arangodb.com/v1
kind: ArangoDeployment
metadata:
  name: single-arango-server
  labels:
    {{- include "labels" . | indent 4 }}
    app.kubernetes.io/component: arango
spec:
  image: docker.io/tothr1112/arangotestimage:latest
  imagePullPolicy: {{ .Values.pullPolicy }}
  annotations:
    {{- include "labels" . | indent 4 }}
    app.kubernetes.io/component: arango
  tls:
    caSecretName: None
  mode: Single
  {{- if .Values.arangodb.nodePort }}
  externalAccess:
    nodePort:  {{ .Values.arangodb.nodePort }}
  {{ end }}
  single:
    resources:
      {{- toYaml .Values.arangodb.resources | nindent 6 }}
```

And if I'm right, the main problem is that specifically the arango container(from ArangoDeployment) must run these init scripts I need, other containers can't run the scripts (I get `ArangoError 2001: not connected` error if I try to run them from other container). That's why also jobs are useless in this case, they run in their own containers.

I also tried to specify single.entrypoint and set it to the entrypoint of the docker image, but then the pod wouldn't even start.

You mentioned ArangoJob, I couldn't find any info on it. Maybe that could solve the ArangoError problem I had with regular jobs. If you still think that can solve this problem, I would gladly accept some help with that.
