### ISSUE TITLE
Custom entrypoint modifies version-check entrypoint too in ArangoDeployment

### ISSUE THREAD

**Issue by ricsi046** [arangodb/kube-arangodb#1426]
Consider this template:

```
apiVersion: database.arangodb.com/v1
kind: ArangoDeployment
metadata:
  name: single-arango-server
  labels:
    {{- include "labels" . | indent 4 }}
    app.kubernetes.io/component: arango
spec:
  image: {{ .Values.repository }}/{{ .Values.arangodb.image.name }}:{{ .Values.arangodb.image.version }}
  imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - docker-registry-key
  annotations:
    {{- include "labels" . | indent 4 }}
    app.kubernetes.io/component: arango
  tls:
    caSecretName: None
  mode: Single
  {{- if .Values.arangodb.nodePort }}
  externalAccess:
    nodePort:  {{ .Values.arangodb.nodePort }}
  {{ end }}
  single:
    resources:
      {{- toYaml .Values.arangodb.resources | nindent 6 }}
    entrypoint:
      sh
    args:
      ["/entrypoint.sh", "arangod"]
```

This will result in the version-check container running the entrypoint.sh script (which starts arangodb and runs indefinitely) so the version-check container never stops, the server container (that should run the entrypoint.sh script) just keeps waiting for the version-check container to exit.

Is this the expected behaviour? I would image it should work like the init-lifecycle, uuid and version-check containers run their own entrypoint (regardless if there is a custom entrypoint set or not), and the custom entrypoint should belong only to the server container.

**Comment by nikita-vanyasin** [comment]
Hello @ricsi046 

Thank you for report.

1) Operator expects that the provided arangod image is compatible with official arangod images. Looks like your changes are not compatible - version check arguments are not handled properly. If you are providing new entrypoint please make sure it can handle the commands which operator expects to be handled. I think we are not going to change the operator behavior here, especially because it seems impossible to do in backward-compatible way without introducing new fields for ArangoDeployment CR.
2) Can you please clarify the use-case why you are modifying entrypoint and arguments for the arangod?
3) I can also recommend using `--deployment.feature.upgrade-version-check-V2=true` option for operator. It will use different implementation for version-check init container which does not rely on arangod binary and works much faster. This is available since operator v1.2.31 and will be enabled by default with next release of operator (1.2.34).
4) Alternative: you can disable version check container at all using `--deployment.feature.upgrade-version-check=false`.

Best,
Nikita

**Comment by ricsi046** [comment]
Hello

We have some arango UDFs that we want to import when the database is starting. The official arangodb image (https://hub.docker.com/_/arangodb) has an entrypoint script that not just starts the database, but also imports UDFs, that's why I tried using it.

In my local environment the custom entrypoint worked fine because there was no version-check (probably because I have no persistent database), but it didn't work in the remote kubernetes cluster with persistent database.

It would probably be better if I could just run an import script instead of overriding the entrypoint, but I couldn't find a way to do that. The script needs to be run by the container that runs the database, so jobs are not an option (they give `ArangoError 2001: not connected` error).

**Comment by nikita-vanyasin** [comment]
hi @ricsi046 
Thank you for sharing!

I think you can embed UDFs by adding new init container via ArangoDeployment spec.
Please check this link: https://github.com/arangodb/kube-arangodb/blob/master/docs/api/ArangoDeployment.V1.md#specsingleinitcontainerscontainers-corecontainer

Basically you can just add new init container like:
```
spec:
  # ...
  single:
    initContainers:
      containers:
        - # define a normal container ( https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#container-v1-core ) which will just copy files
      # optional mode: https://github.com/arangodb/kube-arangodb/blob/master/pkg/apis/deployment/v1/server_group_init_containers.go#L80
      mode: 'ignore' # 'ignore' or 'update'
```

This feature is not documented properly but we are now working on improving documentation 👌🏻 

Best,
Nikita

**Comment by ricsi046** [comment]
Sounds good, I will check this out. Thank you

**Comment by ricsi046** [comment]
I checked it, but this is not working unfortunately. When the init container runs, arangodb is not started, so my init script can't add UDFs to the database (getting `ArangoError 2001: not connected` error from `arangosh`).

I've heard about ArangoJob which I assumed to be a special job that can run `arangosh` commands. So I enabled them when installing the operator, and wrote a job:
```
apiVersion: apps.arangodb.com/v1
kind: ArangoJob
metadata:
  name: init-arango-job
spec:
  arangoDeploymentName: single-arango-server
  jobTemplate:
    template:
      spec:
        containers:
          - name: init-arango
            image: <image>
            command: ["sh", "init_arango.sh"]
        restartPolicy: Never
    backoffLimit: 4
```

The init_arango.sh script contains a few `arangosh` calls, but I get the same `ArangoError 2001: not connected` message like if it was a regular kubernetes job. Am I doing something wrong? Or what is an ArangoJob for if not for running `arangosh` commands?
The ArangoJob waits for the ArangoDeployment to be up, I checked it, so that works fine, the server is running when the job is executed. Is there anything I'm missing?
