### ISSUE TITLE
Issue setting NUMA to interleaved

### ISSUE THREAD

**Issue by JoelWesleyReed** [arangodb/kube-arangodb#1428]
### Description

Using the suggested configuration to set NUMA to interleaved in issue #1366, I get an error starting the ArangoDB container.

### Configuration Snippet
```
spec:
  agents:
    count: 1
    numactl:
      enabled: true
      args:
      - --interleave=all
    volumeClaimTemplate:
      metadata:
        name: local-agent
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "local-arangodb"
        resources:
          requests:
            storage: 2Gi
```

### ArangoDB Container Error
```
Defaulted container "server" out of: server, exporter, init-lifecycle (init), uuid (init), version-check (init)
Error while processing command-line options for arangod:
  unknown option '--interleave'

Did you mean one of these?
  --console      Start the server with a JavaScript emergency console.
  --define       Define a value for a `@key@` entry in the configuration file using the syntax `"key=value"`.
  --fortune      Show a fortune cookie on startup.
  --log.level    Set the topic-specific log level, using `--log.level level` for the general topic or `--log.level topic=level` for the specified topic (can be specified multiple times).
Available log levels: fatal, error, warning, info, debug, trace.
Available log topics: all, agency, agencycomm, agencystore, aql, arangosearch, authentication, authorization, backup, bench, cache, cluster, communication, config, crash, development, dump, engines, flush, general, graphs, heartbeat, httpclient, libiresearch, license, maintenance, memory, mmap, pregel, queries, rep-state, replication, replication2, requests, restore, rocksdb, security, ssl, startup, statistics, supervision, syscall, threads, trx, ttl, v8, validation, views.

Use --help or --help-all to get an overview of available options
```

### Environment

- kube-arangodb 1.2.33
- ArangoDB 3.11.3
- Ubuntu 20.04.6
