### ISSUE TITLE
Cannot change server.endpoint when deploy mode cluster

### ISSUE THREAD

**Issue by trantuancnt** [arangodb/kube-arangodb#1598]
Hi Team,
I deploy Arangodb on k8s with mode cluser simple.
When pod running Faild.
Check log I see `FATAL [c81f6] {general} failed to bind to endpoint 'http+tcp://[::]:8529'. Please check whether another instance is already running using this endpoint and review your endpoints configuration.`

File yaml deploy:

```yaml
apiVersion: "database.arangodb.com/v1"
kind: "ArangoDeployment"
metadata:
  name: "arangodb-cluster"
spec:
  mode: Cluster
  environment: Production
  agents:
    count: 3
    args:
      - --log.level=debug
    resources:
      requests:
        storage: 8Gi
    storageClassName: arangodb-storage
  dbservers:
    count: 3
    resources:
      requests:
        storage: 80Gi
    storageClassName: arangodb-storage
  coordinators:
    count: 3
  image: "arangodb/arangodb:3.11.7"
```

Please help me, thanks.

**Comment by ajanikow** [comment]
Hello!

It looks like your ipv6 is disabled - please set https://arangodb.github.io/kube-arangodb/docs/api/ArangoDeployment.V1.html#specdisableipv6

Like:
```
apiVersion: "database.arangodb.com/v1"
kind: "ArangoDeployment"
metadata:
  name: "arangodb-cluster"
spec:
  mode: Cluster
  environment: Production
  disableIPv6: true
  agents:
    count: 3
    args:
      - --log.level=debug
    resources:
      requests:
        storage: 8Gi
    storageClassName: arangodb-storage
  dbservers:
    count: 3
    resources:
      requests:
        storage: 80Gi
    storageClassName: arangodb-storage
  coordinators:
    count: 3
  image: "arangodb/arangodb:3.11.7"
```

Best Regards,
Adam.
