### ISSUE TITLE
The labels of the exporter service don’t match the selector match labels of the service monitor

### ISSUE THREAD

**Issue by rohde-spread** [arangodb/kube-arangodb#1672]
So the service monitor does not pick up the exporter service.

**Comment by kmrhemant916** [comment]
Because of this no metrics are getting exported.

**Comment by ajanikow** [comment]
Hello!

We have checked it - code, which generates ServiceMonitor, should target the port exporter with label selector matching all Pods.

Also, checked on our TestClusters, all our instances are fine.

Can you share ServiceMonitor yaml?

Best,
Adam.

**Comment by rohde-spread** [comment]
Maybe it's too early in the morning for me but it should match the Service labels, not Pod?
This is the yaml that **works**, for me:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: arangodb-exporter
spec:
  endpoints:
    - bearerTokenSecret:
        key: ''
      interval: 10s
      port: exporter
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      arango_deployment: arangodb
      arango_exporter: 'yes'
```
