### ISSUE TITLE
Error: InvalidImageName

### ISSUE THREAD

**Issue by drago19sk** [arangodb/kube-arangodb#1682]
Hi, 

I'm trying to install Arango Cluster via operator (version 1.2.41) but every time I get this error message: 

Error: InvalidImageName

Failed to apply default image tag "550e8f2ea6e1752cacc937faa13cb01fd00601ebd56bde553094048d2df8afba": couldn't parse image name "550e8f2ea6e1752cacc937faa13cb01fd00601ebd56bde553094048d2df8afba": invalid repository name (550e8f2ea6e1752cacc937faa13cb01fd00601ebd56bde553094048d2df8afba), cannot specify 64-byte hexadecimal strings

I have tried a brand new cluster on Oracle Cloud both Kubernetes version 1.28.2 and 1.29.2. It always throws the same issue. It doesn't matter if I install the operator via Helm or Kubectl.

**Comment by ajanikow** [comment]
Ref: https://github.com/arangodb/kube-arangodb/issues/1509

**Comment by ajanikow** [comment]
Hello!

Please, take a look at the issue attached in the commend above - the issue is related to the CRI-O Version, which can be workaround using Operator args.

Best Regards,
Adam.

**Comment by drago19sk** [comment]
Hello @ajanikow , 

thanks for your reply. 

I downloaded arango-deployment.yaml from this URL: https://raw.githubusercontent.com/arangodb/kube-arangodb/1.2.41/manifests/arango-deployment.yaml and add args --image.discovery.status=false into operator container section:


      containers:
        - name: operator
          imagePullPolicy: Always
          image: arangodb/kube-arangodb:1.2.41
          args:
            - --scope=legacy
            - --operator.deployment
            - --mode.single
            - --chaos.allowed=false
            - --image.discovery.status=false

After deploying into Kubernetes and then trying to deploy the Arango cluster, I had the same issue with the image name.
But it is not working. Please explain where or how I can add this flag (--image.discovery.status=false) to Operator Args.

Thank you very much.

**Comment by ajanikow** [comment]
@drago19sk Can you share your Pod yaml and ArangoDeployment?

+ did you add imageDiscovery mode flag?

**Comment by drago19sk** [comment]
@ajanikow ,

Thank you very much. Now it is working perfectly.

Just recap maybe for other people with the same issue:

1. Download and edit this file https://raw.githubusercontent.com/arangodb/kube-arangodb/1.2.41/manifests/arango-deployment.yaml

In the container section for the operator add a new flag into args (**--image.discovery.status=false**): 

```
containers:
    - name: operator
      imagePullPolicy: Always
      image: arangodb/kube-arangodb:1.2.41
      args:
        - --scope=legacy
        - --operator.deployment
        - --mode.single
        - --chaos.allowed=false
        - --image.discovery.status=false
```

2. Download ArangoDeploymnet ( I used a production cluster example) and add 
**imageDiscoveryMode: 'direct'** like this:

```
apiVersion: "database.arangodb.com/v1"
kind: "ArangoDeployment"
metadata:
  name: "production-cluster"
spec:
  metrics:
    mode: sidecar
    enabled: true
    image: 'arangodb/arangodb-exporter:0.1.8'
    tls: false
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9101'
    prometheus.io/scrape_interval: '5s'
  mode: Cluster
  image: 'arangodb/arangodb:3.12.0.2'
  imageDiscoveryMode: 'direct'
  environment: Production
```
