### ISSUE TITLE
<deployment>-jwt-folder secret is missing

### ISSUE THREAD

**Issue by vfouqueron** [arangodb/kube-arangodb#1685]
I just tried to deploy arango in my Kubernetes cluster in version 1.2.41. The pod fails instantly with no error.

In the arango-arangodb-operator, I have the following error :
`Unable to get secret error="secrets \"arangodb-jwt-folder\" not found" name=arangodb namespace=arango operator-id=phrlx`

I found similar issue https://github.com/arangodb/kube-arangodb/issues/993 but it describes an issue solved two years ago. ANy idea on what is happening ?

Here is my ArangoDeployment : 
```
apiVersion: database.arangodb.com/v1
kind: ArangoDeployment
metadata:
  name: arangodb
  namespace: ${module.k8s_namespace.namespace}
spec:
  agents:
    volumeClaimTemplate:
      spec:
        storageClassName: ${var.storage_classname}
  dbservers:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: ${var.storage_classname}
  mode: Cluster
  timezone: "Europe/Paris"
```
