### ISSUE TITLE
[BUG] Failed to create ArangoDeployment since imagePullSecrets is not recognized correctly

### ISSUE THREAD

**Issue by lianneli** [arangodb/kube-arangodb#1825]
My ArangoDeployment YAML：

```yaml
apiVersion: "database.arangodb.com/v1"
kind: "ArangoDeployment"
metadata:
  name: "arangodb"
spec:
  mode: Single
  image: xxx.xxx/arangodb/arangodb:3.12.4
  imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - name: xxx-xxx-secret
  single:
    volumeClaimTemplate:
      spec:
        storageClassName: xxx-sci
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        volumeMode: Filesystem

```

BUT Error happened in operator:
```
W0217 07:43:34.600934       1 reflector.go:561] pkg/util/k8sutil/informer.go:100: failed to list *v1.ArangoDeployment: json: cannot unmarshal object into Go struct field DeploymentSpec.items.spec.imagePullSecrets of type string
E0217 07:43:34.600970       1 reflector.go:158] "Unhandled Error" err="pkg/util/k8sutil/informer.go:100: Failed to watch *v1.ArangoDeployment: failed to list *v1.ArangoDeployment: json: cannot unmarshal object into Go struct field DeploymentSpec.items.spec.imagePullSecrets of type string" logger="UnhandledError"

```

Which means the `imagePullSecrets` is not recognized correctly.

**Comment by ajanikow** [comment]
Hello!

Ref: https://arangodb.github.io/kube-arangodb/docs/api/ArangoDeployment.V1.html#specimagepullsecrets

It is list of strings, not the format which is in the Pod.

Use:

```yaml
apiVersion: "database.arangodb.com/v1"
kind: "ArangoDeployment"
metadata:
  name: "arangodb"
spec:
  mode: Single
  image: xxx.xxx/arangodb/arangodb:3.12.4
  imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - "xxx-xxx-secret"
  single:
    volumeClaimTemplate:
      spec:
        storageClassName: xxx-sci
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        volumeMode: Filesystem
```

Best Regards,
Adam
