### ISSUE TITLE
Incorrect Pod Labels Applied by ArangoDB Kubernetes Operator

### ISSUE THREAD

**Issue by Dibz15** [arangodb/kube-arangodb#1847]
**Description:**
When deploying an `ArangoDeployment` in `Single` mode, the created pods are labeled incorrectly. Despite explicitly specifying a pod label as `role: single` in the `ArangoDeployment` CRD, the operator consistently labels pods with `role: id`. This mismatch breaks service selectors and prevents the service from routing traffic correctly.

**Affected Component:**
ArangoDB Kubernetes Operator

**Operator Version:** 1.2.44

**Kubernetes Distribution and Version:**
K3s v1.32.1

**Expected Behavior:**
When specifying labels explicitly in the `ArangoDeployment`, pods created by the operator should use those labels. For example:

```yaml
spec:
  mode: Single
  single:
    labels:
      role: single
```

Pods should have labels:
```
app=arangodb
arango_deployment=single-server
role=single
```

**Actual Behavior:**
Pods are incorrectly labeled with:
```
app=arangodb
arango_deployment=single-server
role=id
```

**Steps to Reproduce:**
1. Deploy the ArangoDB Operator via Helm.
2. Create an `ArangoDeployment` with explicit labels as shown above.
3. Observe pod labels after deployment.

**Workaround:**
Manually creating a separate Kubernetes Service that matches the operator-generated pod labels:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: arango-single-server-custom
spec:
  type: LoadBalancer
  ports:
    - port: 8529
      targetPort: 8529
  selector:
    app: arangodb
    arango_deployment: single-server
    role: id
```

**Suggested Fix:**
Ensure the operator correctly applies labels specified in the `ArangoDeployment` resource definition.

**Additional Information:**
- Kubernetes version:
Client Version: v1.31.5+k3s1
Kustomize Version: v5.4.2
Server Version: v1.31.5+k3s1
