### ISSUE TITLE
multi-node ArangoDB cluster in a same machine

### ISSUE THREAD

**Issue by kulta4** [arangodb/kube-arangodb#1919]
Hi,

can deploy the arangoDB cluster with agent 3, coordinator 2, prmr 3 in a same machine by adding this custom yaml

```
  apiVersion: database.arangodb.com/v1
  kind: ArangoDeployment
  metadata:
    name: arangodb-cluster
    namespace: arangodb
  spec:
    environment: Development
    mode: Cluster
    image: "arangodb/arangodb:latest"
    agents:
      count: 3
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
    dbservers:
      count: 3
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
    coordinators:
      count: 2
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
    auth:
      enabled: false
```
and used helm version
```

export URLPREFIX=https://github.com/arangodb/kube-arangodb/releases/download/1.2.49
helm install --generate-name $URLPREFIX/kube-arangodb-1.2.49.tgz
```
with this I am getting 401 while trying to check the health. I try changing the yaml of deployment/cluster-coordinator by removing all the auth still same.
