### ISSUE TITLE
CRD for arango deployment not deleting

### ISSUE THREAD

**Issue by Hugheym** [arangodb/kube-arangodb#263]
I'm trying to delete the arango crd using kubectl delete, but it is stuck at "CustomResource deletion is in progress". I've already deleted all other arango resources in the cluster and there are no arangoDeployments currently running. My master and node versions are at 1.10.7-gke.6 and I'm running on GKE with istio. 
```yaml
 >>>kubectl describe crd/arangodeployments.database.arangodb.com

Name:         arangodeployments.database.arangodb.com
Namespace:
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"name":"arangodeployments.database.arangodb...
API Version:  apiextensions.k8s.io/v1beta1
Kind:         CustomResourceDefinition
Metadata:
  Creation Timestamp:             2018-09-30T13:25:29Z
  Deletion Grace Period Seconds:  0
  Deletion Timestamp:             2018-10-13T08:22:05Z
  Finalizers:
    customresourcecleanup.apiextensions.k8s.io
  Generation:        1
  Resource Version:  16979330
  Self Link:         /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/arangodeployments.database.arangodb.com
  UID:               4cc9630e-c4b4-11e8-b22a-42010a92012a
Spec:
  Group:  database.arangodb.com
  Names:
    Kind:       ArangoDeployment
    List Kind:  ArangoDeploymentList
    Plural:     arangodeployments
    Short Names:
      arangodb
      arango
    Singular:  arangodeployment
  Scope:       Namespaced
  Version:     v1alpha
Status:
  Accepted Names:
    Kind:       ArangoDeployment
    List Kind:  ArangoDeploymentList
    Plural:     arangodeployments
    Short Names:
      arangodb
      arango
    Singular:  arangodeployment
  Conditions:
    Last Transition Time:  2018-09-30T13:25:29Z
    Message:               no conflicts found
    Reason:                NoConflicts
    Status:                True
    Type:                  NamesAccepted
    Last Transition Time:  2018-09-30T13:25:29Z
    Message:               the initial names have been accepted
    Reason:                InitialNamesAccepted
    Status:                True
    Type:                  Established
    Last Transition Time:  2018-10-13T06:17:12Z
    Message:               CustomResource deletion is in progress
    Reason:                InstanceDeletionInProgress
    Status:                True
    Type:                  Terminating
Events:                    <none>
```
