### ISSUE TITLE
Arango + Foxx + K8s

### ISSUE THREAD

**Issue by adian** [arangodb/kube-arangodb#395]
Hi,

We are using arangoDB + Foxx as our services' db. For now, we are creating docker images using a script which creates an image and adds foxx service via HTTP. Can I use that image with arango operator? 

I was trying 
```yml
apiVersion: "database.arangodb.com/v1alpha"
kind: "ArangoDeployment"
metadata:
  name: "arango-single-no-tls"
spec:
  mode: Single
  tls:
    caSecretName: None
  image: mynexus/myimage:1.2.3
```
but it doesn't work. It pulls default image.
