### ISSUE TITLE
Cannot access the ArangoDB database 

### ISSUE THREAD

**Issue by averri** [arangodb/kube-arangodb#502]
I was not able to reproduce the examples in the documentation. I have created the single server example as documented here: https://github.com/arangodb/kube-arangodb/blob/master/docs/Manual/Tutorials/Kubernetes/README.md

```bash
kubectl apply -f https://raw.githubusercontent.com/arangodb/kube-arangodb/0.4.2/manifests/arango-crd.yaml
kubectl apply -f https://raw.githubusercontent.com/arangodb/kube-arangodb/0.4.2/manifests/arango-deployment.yaml
kubectl apply -f https://raw.githubusercontent.com/arangodb/kube-arangodb/0.4.2/manifests/arango-deployment-replication.yaml
```

Using the single server:
```bash
apiVersion: "database.arangodb.com/v1alpha"
kind: "ArangoDeployment"
metadata:
  name: "single-server"
spec:
  mode: Single
```

```bash
kubectl apply -f single-server.yaml
```

I cannot access the ArangoDB database, the service does not expose the **external IP** using LoadBalancer or NodePort:

```bash
 kubectl get svc single-server-ea
NAME               TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
single-server-ea   NodePort   10.43.206.147   <none>        8529:30007/TCP   119s
```

**Comment by informalict** [comment]
Have you got some errors in logs? :
```
kubectl logs $(kubectl get pods --selector=app.kubernetes.io/name=kube-arangodb -o=jsonpath='{.items[0].metadata.name}')
```

**Comment by averri** [comment]
I have configured a `ArangoLocalStorage` using:

```
apiVersion: "storage.arangodb.com/v1alpha"
kind: "ArangoLocalStorage"
metadata:
  name: "arangodb-local-storage"
spec:
  storageClass:
    name: my-local-ssd
    isDefault: true
  localPath:
  - /var/lib/arangodb3
```

And this is the error from `single-server-ea`:

```
MountVolume.NewMounter initialization failed for volume "arangodb-local-storage-a89d69-jnieaw6kdxyb34mk" : path "/var/lib/arangodb3/jnieaw6kdxyb34mk" does not exist
```
