### ISSUE TITLE
Backup with Minio not working

### ISSUE THREAD

**Issue by waclawikj** [arangodb/kube-arangodb#506]
I have set up Minio server with helmchart and in the same namespace i am trying to make backup resource that uploads to this server 
```
apiVersion: "backup.arangodb.com/v1alpha"
kind: "ArangoBackup"
metadata:
  name: "example-arangodb-backup"
  namespace: "test"
spec:
  deployment:
    name: "arangodb-cluster"
  options:
    timeout: 3
    force: true
  upload:
    repositoryURL: "minio://bucket/test"
    credentialsSecretName: "miniosecret"
```

using secret with token encoded from json:
```
{
    "S3": {
        "type": "s3",
        "provider": "Minio", 
        "env_auth": "false", 
        "access_key_id": "myaccesskey",
        "secret_access_key": "mysecretkey",
        "acl": "private", 
        "endpoint": "minio:9000",
     }
}
```
Resource has been created, but with no info
![image](https://user-images.githubusercontent.com/52488043/70152103-e62b3a00-16ac-11ea-8e04-39809e231845.png)
minio server is empty and operator logs don't say anything about creating this resource

Am i doing something wrong?
