### ISSUE TITLE
How to expose dashboard and/or web interface using an ingress

### ISSUE THREAD

**Issue by couds** [arangodb/kube-arangodb#523]
Hi All. Im trying to expose the web interface using a service and a ingress but I got and 502 error. 

This is the configuration.

```
apiVersion: "database.arangodb.com/v1alpha"
kind: "ArangoDeployment"
metadata:
  name: "arango"
  namespace: arangodb
spec:
  mode: Cluster
  image: arangodb/arangodb:3.6.1
  environment: Production
  externalAccess:
    type: None
---
kind: Service
apiVersion: v1
metadata:
  name: arangodb-cluster
  namespace: arangodb
spec:
  selector:
    arango_deployment: arangodb-cluster
    role: coordinator
  ports:
  - protocol: TCP
    port: 8529
    targetPort: 8529
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: arango
  namespace: arangodb
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/service-upstream: "true"
spec:
  tls:
  - hosts:
    - db.mydomain.com
    secretName: arango-tls
  rules:
  - host: db.mydomain.com
    http:
      paths:
      - path: /
        backend:
          serviceName: arangodb-cluster
          servicePort: 8529
``` 

Any Ideas?
