### ISSUE TITLE
dbservers stuck on default storageClassName standard instead of the deployment specification

### ISSUE THREAD

**Issue by mizunos** [arangodb/kube-arangodb#525]
Operator v 0.4.4
Arangodb v 3.6.1 running on GKE (enterprise edition)
I have the following definition for an arango single server in ActiveFailover mode and a storageClass object definition for ssd

```
  agents:
    nodeSelector:
      dbtype: arango
    count: 3
    args:
      - --log.level=debug
    storageClassName: ssd
    resources:
      requests:
        storage: 8Gi
  dbservers:
    nodeSelector:
      dbtype: arango
    count:  2
    storageClassName: ssd
    resources:
      requests:
        storage: 30Gi
  externalAccess:
    type: None
```

For whatever reason, only the agents nodes use ssd.  dbserver nodes insist on using the default storage (in this case, "standard")

I had to patch kubeconfig to switch the whole cluster to default on ssd in order for the dbserver to use ssd as persistent volume -  

This is the same behavior problem for arangodb in cluster mode deployed on GKE.

Desired state is for dbserver to  use storage defined in storageClass instead of just the default for the cluster.
