### ISSUE TITLE
web service different path

### ISSUE THREAD

**Issue by damianoneill** [arangodb/kube-arangodb#589]
Hi, I've defined an ingress for the web service.  I'm using nginx as the ingress controller.

```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: arango-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
  - http:
      paths:
      - path: /arango
        backend:
          serviceName: example-simple-single-int
          servicePort: 8529
---
```

I'd like to define a different path (I have multiple paths exposed on the ingress to different backing services).  

Is there a base url variable or env variable in the operator I can set to instruct the web service to serve content from /arango rather than / ?
