### ISSUE TITLE
Allow the use of init containers in the deployment config

### ISSUE THREAD

**Issue by curtdept** [arangodb/kube-arangodb#613]
So I can set thing like transparent hugepage settings, vm.max_map_count, etc prior to container start.

I see some initContainers already there, there just doesnt seem to be a way to append to it.

A shortcut flag that auto applies recommended config in an init would also be helpful.

**Comment by iMoses** [comment]
+1

There's no way to address Max Memory Mappings without creating my own custom images.
Please support passing `initContainer` config.

**Comment by curtdept** [comment]
Wordaround atm with a DaemonSet

`apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sysctl
  namespace: arango
spec:
  selector:
    matchLabels:
      aikido: sysctl
  template:
    metadata:
      labels:
        aikido: sysctl
    spec:
      hostNetwork: yes
      initContainers:
      - name: sysctl
        image: "busybox"
        securityContext:
          privileged: true
        command: ['sh', '-c', 'sysctl -w vm.max_map_count=256000 && echo madvise > /sys/kernel/mm/transparent_hugepage/enabled && echo madvise > /sys/kernel/mm/transparent_hugepage/defrag']
      containers:
        - name: sleep
          image: filefrog/k8s-hacks:pause`

**Comment by ajanikow** [comment]
Hello!

Fixed with PR #650 

Best Regards,
Adam.

**Comment by curtdept** [comment]
@ajanikow if I read this right, just initContainers under the appropriate servergroup?

ie.
spec:
  agents:
    initContainers:
      - name: sysctl
    image: busybox
    securityContext:
      privileged: true
    command:
      - sh
      - '-c'
      - >-
        sysctl -w vm.max_map_count=256000 && echo madvise >
        /sys/kernel/mm/transparent_hugepage/enabled && echo madvise >
        /sys/kernel/mm/transparent_hugepage/defrag


Going to update the docs with an example?

**Comment by iMoses** [comment]
> @ajanikow if I read this right, just initContainers under the appropriate servergroup?

You actually have to dig deep in undocumented code to figure how the new mechanism works.

User the service group you can add:
```
initContainers:
  mode: update  // weather to recreate pods on changes to initContainers, can also be "ignore"
  containers:
    - name: sysctl
      image: busybox
      securityContext:
        privileged: true
      command: ['sh', '-c', 'sysctl -w vm.overcommit_memory=0 vm.max_map_count=262144']
```

I really wish it was documented or at the very least had tests, it took me quite a while to find.
