### ISSUE TITLE
Disabling TLS / unable to rotate pods via annotation

### ISSUE THREAD

**Issue by radicaled** [arangodb/kube-arangodb#660]
For the purposes of testing ArangoDB, we deployed a cluster like this:

```yaml
apiVersion: database.arangodb.com/v1alpha
kind: ArangoDeployment
metadata:
  name: arangodb-cluster
spec:
  mode: Cluster
  image: arangodb/arangodb:3.7.3
```

After testing, we decided to disable TLS:

```yaml
apiVersion: database.arangodb.com/v1alpha
kind: ArangoDeployment
metadata:
  name: arangodb-cluster
spec:
  mode: Cluster
  image: arangodb/arangodb:3.7.3
  tls:
      caSecretName: None
  downtimeAllowed: true
```

However, unexpectedly, the deployment doesn't rotate the pods automatically. After several hours of Googling, we found https://github.com/arangodb/kube-arangodb/blob/master/docs/design/rotating.md -- not linked or documented on arangodb.com by the way.

However, applying the annotations to each pod in the cluster doesn't seem to have any effect. In the event log, the ArangoDeployment just keeps adding the 'Idle' plan type over and over again.

Short of completely nuking each pod manually (and possibly incuring data loss), what's the best way to resolve this as well as rotate pods in the future whenever we make a change?
