### ISSUE TITLE
Community edition backups

### ISSUE THREAD

**Issue by mj3c** [arangodb/kube-arangodb#671]
Are backups when using the Community edition possible using the K8s operator in any way? I am not sure if and where I missed it in the documentation, but I didn't find any information regarding this until I tried it and saw that it failed. Then I came upon issue https://github.com/arangodb/kube-arangodb/issues/507.

Is there a plan to support backups using the operator?

**Comment by ajanikow** [comment]
Hello!

There is no API for that in Community edition, same feature can be achieved by arangodump and K8S CronJob - Operator does not have local storage, so it wont be able to do backup for you to local storage.

Best Regards,
Adam Janikowski.

**Comment by mj3c** [comment]
Hey @ajanikow , thanks for answering!

How would you recommend to do this using a K8s CronJob and arangodump? Would the Job access the existing ArangoDB pod/container using `kubectl exec` in order to perform arangodump there, or is there something else I am missing? Any directions would be very appreciated.

**Comment by ajanikow** [comment]
Hello!

Docs: https://www.arangodb.com/docs/stable/programs-arangodump.html

In principal: Job, which is scheduled by CronJob, should execute this with proper url and credentials. Dump should be saved on PVC to persist it. I will try to find doc for CronJob description for linux, which can be easily moved

Best Regards,
Adam.

**Comment by mj3c** [comment]
Thanks for the info! 

The fact that I can run arangodump in another pod (and not only on the one that's running the db) totally went over my head.

For anyone else wondering, you can create a dump and upload it to S3 (or download it from S3 and restore it) using a Job/CronJob with a pod spec as show below:

```yaml
spec:
  initContainers:
    - name: dump-create
      image: "arangodb:3.7.3"
      args:
        - "arangodump"
        - "--server.endpoint=ssl://arangodb:8529"
        - "--server.username=$(username)"
        - "--server.password=$(password)"
        - "--server.database=db_name"
        - "--output-directory=/tmp/dump"
      volumeMounts:
        - name: dump
          mountPath: /tmp/dump
  containers:
    - name: db-dump-upload
      image: amazon/aws-cli:2.1.4
      command: ["/bin/sh", "-c"]
      args: ["aws s3 sync /tmp/dump s3://bucket/dump-dir"]
      volumeMounts:
        - name: dump
          mountPath: /tmp/dump
  volumes:
    - name: dump
      emptyDir: {}
```

Of course, missing env vars need to be added. Also, arangodump and arangorestore support the `--configuration` file option, so that can be used as well.
