### ISSUE TITLE
Unable to deploy more than one cluster with Operator

### ISSUE THREAD

**Issue by ognjen-it** [arangodb/kube-arangodb#758]
Hi everyone,
I deployed arangodb-operator-crd and arangodb-operator to manage my ArangoDB cluster.
When I deploy the first cluster, it was working. However, when I tried to deploy the second one, I sow next error message:

> DBG Failed to fetch deployment health error="JWT Secret is missing" component=deployment deployment=ognjenarangodb-cluster operator-id=jb7p9

If I create the secret manually, the operator will show the next error (service does not exist):

```
2021-07-20T08:46:52Z DBG Failed to set number of servers error="Put \"https://ognjenarangodb-cluster.arangodb-operator.svc:8529/_admin/cluster/numberOfServers\": dial tcp: lookup ognjenarangodb-cluster.arangodb-operator.svc on 169.254.25.10:53: no such host" component=deployment deployment=ognjenarangodb-cluster operator-id=jb7p9
2021-07-20T08:46:52Z DBG Cluster update failed error="Put \"https://ognjenarangodb-cluster.arangodb-operator.svc:8529/_admin/cluster/numberOfServers\": dial tcp: lookup ognjenarangodb-cluster.arangodb-operator.svc on 169.254.25.10:53: no such host" component=deployment deployment=ognjenarangodb-cluster operator-id=jb7p9

```

**How I deployed arangodb-operator-crd?**

`helm -n arangodb-operator install arangodb-operator-crd https://github.com/arangodb/kube-arangodb/releases/download/1.1.10/kube-arangodb-crd-1.1.10.tgz`

**How I deployed arangodb-operator?**

`helm -n arangodb-operator install ts https://github.com/arangodb/kube-arangodb/releases/download/1.1.10/kube-arangodb-1.1.10.tgz`

**How I deployed cluster?**
```
apiVersion: "database.arangodb.com/v1alpha"
kind: "ArangoDeployment"
metadata:
  name: "ognjenarangodb-cluster"
  namespace: arangodb-operator
spec:
  mode: Cluster
  environment: Production
  image: "arangodb/arangodb:3.7.10"
  imagePullPolicy: IfNotPresent
  agents:
    count: 3
    args:
      - --log.level=debug
    resources:
      requests:
        storage: 4Gi
    storageClassName: rook-ceph-block
  dbservers:
    count: 3
    resources:
      requests:
        storage: 8Gi
    storageClassName: rook-ceph-block
  coordinators:
    count: 3
```

Kubernetes version:
v1.18.8
