### ISSUE TITLE
ActiveFailover deployment readiness probe error

### ISSUE THREAD

**Issue by millerjl1701** [arangodb/kube-arangodb#762]
Transferring conversation over from Slack.

I have an ActiveFailover ArangoDB instance deployed on OpenShift 4.7 with v1.1.9 of the ArangoDB operator. The active and failover servers both exhibit the following error:

```
Readiness probe failed: {"level":"info","path":"/secrets/cluster/jwt/token","time":"2021-07-22T13:04:34Z","message":"Try to use file"} {"level":"info","token":"token","time":"2021-07-22T13:04:34Z","message":"Using JWT Token"} {"level":"error","error":"Unexpected code: 503 - {\"code\":503,\"error\":true,\"errorMessage\":\"service unavailable\",\"errorNum\":503}","time":"2021-07-22T13:04:34Z","message":"Fatal"}
```

After sometime, the ArangoDB will remove the pod and deploy a new one at which point the failover becomes passive, the new becomes the failover, rinse repeat. The pods running the agents in the deployment do not exhibit this behavior.

The deployment was created with:

```yaml
apiVersion: "database.arangodb.com/v1"
kind: "ArangoDeployment"
metadata:
  name: "arangodb-production"
spec:
  mode: ActiveFailover
  single:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 25Gi
  environment: Production
  image: 'arangodb/arangodb:3.7.11'
  imagePullPolicy: Always
  storageEngine: RocksDB
  networkAttachedVolumes: true
  externalAccess:
    type: NodePort
  disableIPv6: true
  bootstrap:
    passwordSecretNames:
      root: Auto
```
