### ISSUE TITLE
alb ingress returns 502 when trying to access ea service

### ISSUE THREAD

**Issue by david-webill** [arangodb/kube-arangodb#801]
Hi

I have installed a simple arango cluster as follows:
```yaml
apiVersion: "database.arangodb.com/v1"
kind: "ArangoDeployment"
metadata:
  name: "arangodb"
spec:
  mode: Single
  image: 'arangodb/arangodb:3.7.10'
  externalAccess:
    type: NodePort
```
My ingress is as follows:
```yaml
{{ if .Values.ingress.enable }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name| lower }}-ingress
  {{- include "chart.labels" .}}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme | lower }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certificate | quote }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.hostname }}
spec:
  rules:
    - host: {{.Values.ingress.hostname}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: arangodb-ea
                port:
                  number: {{ .Values.service.port }}
  {{ end }}
```

the description of the ingress is as follows:
```yaml
k describe ingress arangodb-ingress -n arango
Name:             arangodb-ingress
Namespace:        arango
Address:          k8s-arango-arangodb-redacted
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host                    Path  Backends
  ----                    ----  --------
  arango.webill-test.net  
                          /   arangodb-ea:8529 (10.0.3.188:8529)
Annotations:              alb.ingress.kubernetes.io/actions.ssl-redirect:
                            {"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}
                          alb.ingress.kubernetes.io/certificate-arn: redacted
                          alb.ingress.kubernetes.io/listen-ports: [{"HTTPS":443}]
                          alb.ingress.kubernetes.io/scheme: internet-facing
                          external-dns.alpha.kubernetes.io/hostname: arango.redacted.net
                          kubernetes.io/ingress.class: alb
                          meta.helm.sh/release-name: arangodb
                          meta.helm.sh/release-namespace: arango
```

I can access the ui via the NodePort but not the Ingress?
Anyone been successful with this?
