### ISSUE TITLE
ArangoDB Operator fail with unprivileged PodSecurityPolicy

### ISSUE THREAD

**Issue by ognjen-it** [arangodb/kube-arangodb#808]
Hello all,

I have a problem when I try to install the ArangoDB operator on Kubernetes with an unprivileged policy.
The error looks like:
`Warning  FailedCreate  5m35s (x18 over 16m)  replicaset-controller  Error creating: pods "arango-ts-operator-7c8cf4cf7d-" is forbidden: PodSecurityPolicy: unable to admit pod: []`

The policy is:

```
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restricted
  labels:
    kubernetes.io/cluster-service: "true"
    eks.amazonaws.com/component: pod-security-policy
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
    # apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'runtime/default'
    # apparmor.security.beta.kubernetes.io/defaultProfileName:  'runtime/default'
spec:
  privileged: false
  # Required to prevent escalations to root.
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - 'KILL'
    - 'MKNOD'
    - 'SETUID'
    - 'SETGID'
  # Allow core volume types.
  volumes:
    - configMap
    - downwardAPI
    - emptyDir
    - persistentVolumeClaim
    - projected
    - secret
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    # Require the container to run without root privileges.
    rule: 'MustRunAsNonRoot'
  seLinux:
    # This policy assumes the nodes are using AppArmor rather than SELinux.
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
```

CRD:
helm -n arangodb-operator install arangodb-operator-crd https://github.com/arangodb/kube-arangodb/releases/download/1.2.3/kube-arangodb-crd-1.2.3.tgz
Operator:
helm -n arangodb-operator install ts https://github.com/arangodb/kube-arangodb/releases/download/1.2.3/kube-arangodb-1.2.3.tgz

Does anyone know how to resolve that? Or is it possible to resolve that? 
#677 This problem may be related

**Comment by ajanikow** [comment]
Hello!

ArangoMember Pods are prepared to be configured to work in a fully protected environment, but I see that something is missing on the Operator level.

Can you say what is missing in the Deployment template? The operator is not using anything on FileSystem, so change can be propagated easily.

Best Regards,
Adam.

**Comment by ognjen-it** [comment]
Hi @informalict 

Thank you for your response!
First of all, I delete privileged PodSecurityPolicy (PSP) and then create unprivileged PSP. After that, I create Role and RoleBinding witch is apply the unprivileged policy to all authenticated users.

Role and RoleBing:

```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ognjen-allow-role
  namespace: ognjen-restrict
  labels:
    kubernetes.io/cluster-service: "true"
    eks.amazonaws.com/component: pod-security-policy
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - restricted
```
```
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ognjen-allow-rolebinding
  namespace: ognjen-restrict
  labels:
    kubernetes.io/cluster-service: "true"
    eks.amazonaws.com/component: pod-security-policy
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: system:authenticated
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ognjen-allow-role
```

**Comment by informalict** [comment]
@ognjen-it please try the following excerpt:
```
apiVersion: "database.arangodb.com/v1alpha"
kind: "ArangoDeployment"
metadata:
  name: "example-arangodb-cluster"
  namespace: arangodb-operator
spec:
  mode: Cluster
  environment: Production
  id:
    securityContext:
      runAsUser: 1000
  image: "arangodb/arangodb:3.7.15"
  imagePullPolicy: IfNotPresent
  metrics:
    mode: sidecar
    enabled: true
    image: 'arangodb/arangodb-exporter:0.1.8'
    tls: false
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9101'
    prometheus.io/scrape_interval: '5s'
  agents:
    count: 3
    args:
      - --log.level=info
    resources:
      requests:
        storage: 4Gi
    securityContext:
      runAsUser: 1000
    storageClassName: gp2
  dbservers:
    count: 3
    args:
      - --log.level=info
    resources:
      requests:
        storage: 8Gi
    securityContext:
      runAsUser: 1000
    storageClassName: gp2
  coordinators:
    count: 3
    args:
      - --log.level=info
    securityContext:
      runAsUser: 1000
```

I have added:
```
    securityContext:
      runAsUser: 1000
```
to run all containers as non-root. You can change the user 1000 to something else if it is necessary.
